import { execSync } from 'child_process';
import { builtinModules } from 'node:module';
import { resolve } from 'path';
import { defineConfig } from 'vite';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(({ mode }) => ({
	build: {
		lib: {
			entry: 'src/main.ts',
			formats: ['cjs'],
			fileName: () => 'main.js',
		},
		rollupOptions: {
			external: [
				'obsidian',
				'electron',
				'@codemirror/autocomplete',
				'@codemirror/collab',
				'@codemirror/commands',
				'@codemirror/language',
				'@codemirror/lint',
				'@codemirror/search',
				'@codemirror/state',
				'@codemirror/view',
				'@lezer/common',
				'@lezer/highlight',
				'@lezer/lr',
				...builtinModules,
			],
			output: {
				banner,
			},
		},
		minify: mode === 'production' ? 'oxc' : false,
		sourcemap: mode === 'production' ? false : 'inline',
		emptyOutDir: true,
		outDir: 'dist',
		reportCompressedSize: false,
	},
	plugins: [
		{
			name: 'deploy-to-vault',
			closeBundle() {
				if (mode === 'development') {
					try {
						const deployScript = resolve(
							process.cwd(),
							'scripts',
							'deploy.mjs',
						);
						execSync(`node "${deployScript}"`, { stdio: 'inherit' });
					} catch {
						// deploy script handles its own errors
					}
				}
			},
		},
	],
}));
