import { builtinModules } from 'node:module';
import { defineConfig } from 'vite';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(({ mode }) => ({
	build: {
		lib: {
			entry: 'src/main.ts',
			formats: ['cjs'],
			fileName: () => 'main.js',
		},
		rollupOptions: {
			external: [
				'obsidian',
				'electron',
				'@codemirror/autocomplete',
				'@codemirror/collab',
				'@codemirror/commands',
				'@codemirror/language',
				'@codemirror/lint',
				'@codemirror/search',
				'@codemirror/state',
				'@codemirror/view',
				'@lezer/common',
				'@lezer/highlight',
				'@lezer/lr',
				...builtinModules,
			],
			output: {
				banner,
			},
		},
		minify: mode === 'production' ? 'oxc' : false,
		sourcemap: mode === 'production' ? false : 'inline',
		emptyOutDir: true,
		outDir: 'dist',
		reportCompressedSize: false,
	},
}));
