name: Release CLI to GitHub Packages

on:
  push:
    tags:
      - 'cli-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 11.13.1

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@gaorun'

      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @gaorun/create-obsidian-plugin run build
      - run: pnpm --filter @gaorun/create-obsidian-plugin publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
